FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY stem-worker-requirements.txt .
ARG TORCH_INDEX_URL=https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir --index-url ${TORCH_INDEX_URL} torch==2.8.0
RUN pip install --no-cache-dir --index-url ${TORCH_INDEX_URL} torchaudio==2.8.0
RUN pip install --no-cache-dir -r stem-worker-requirements.txt
COPY app ./app
CMD ["python", "-m", "app.scripts.stem_worker"]
